target = https://raw.githubusercontent.com/ishiikurisu/checklists/master/lists.yml

compile:
	javac Test.java -cp ./br.eng.crisjr.failproof.jar:.

do: compile
	java -cp ./br.eng.crisjr.failproof.jar:. Test
